# Generated by Django 2.1.4 on 2018-12-06 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('area', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200)),
                ('location_lat', models.FloatField(default=0.0)),
                ('location_lon', models.FloatField(default=0.0)),
                ('location_pub_date', models.DateTimeField(verbose_name='date published')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='area.Area')),
            ],
            options={
                'verbose_name_plural': 'Locations',
            },
        ),
    ]
