# Generated by Django 2.1.4 on 2018-12-06 19:53

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('affective_response', '0003_auto_20181206_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='affectiveresponse',
            name='my_field2',
        ),
        migrations.AlterField(
            model_name='affectiveresponse',
            name='accompany',
            field=models.CharField(choices=[(1, 'Alone'), (2, 'With family member(s)'), (3, 'With friend(s)'), (4, 'With adult(s)'), (5, 'with child(ren)')], default=1, max_length=20),
        ),
        migrations.AlterField(
            model_name='affectiveresponse',
            name='category',
            field=models.CharField(choices=[(1, 'Activities'), (2, 'Social Behavior'), (3, 'Transportation')], default=1, max_length=20),
        ),
        migrations.AlterField(
            model_name='affectiveresponse',
            name='familiarity',
            field=models.CharField(choices=[(1, 'For the first time'), (2, 'More Often')], default=1, max_length=20),
        ),
        migrations.AlterField(
            model_name='affectiveresponse',
            name='feature_set',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Diverse')], default=0, max_length=20),
        ),
    ]
