# Generated by Django 2.1.4 on 2018-12-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affective_response', '0004_auto_20181207_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectiveresponse',
            name='accompany',
            field=models.CharField(choices=[(1, 'Alone'), (2, 'With family member(s)'), (3, 'With friend(s)'), (4, 'With adult(s)'), (5, 'with child(ren)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='affectiveresponse',
            name='category',
            field=models.CharField(choices=[(1, 'Activities'), (2, 'Social Behavior'), (3, 'Transportation')], max_length=20),
        ),
        migrations.AlterField(
            model_name='affectiveresponse',
            name='familiarity',
            field=models.CharField(choices=[(1, 'For the first time'), (2, 'More Often')], max_length=20),
        ),
    ]
