# Generated by Django 2.1.4 on 2018-12-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('category_status', models.BooleanField(choices=[(1, 'Active'), (2, 'Inactive')], default=2)),
                ('category_votes', models.IntegerField(default=0)),
                ('category_pub_date', models.DateTimeField(verbose_name='date published')),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
    ]
