# Generated by Django 2.1.4 on 2018-12-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=200)),
                ('area_lat', models.FloatField(default=0.0)),
                ('area_lon', models.FloatField(default=0.0)),
                ('area_pub_date', models.DateTimeField(verbose_name='date published')),
            ],
            options={
                'verbose_name_plural': 'areas',
            },
        ),
    ]
