# Generated by Django 2.1.4 on 2018-12-06 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=300)),
                ('feature_value', models.IntegerField(default=0)),
                ('feature_status', models.BooleanField(choices=[(1, 'Active'), (2, 'Inactive')], default=2)),
                ('feature_votes', models.IntegerField(default=0)),
                ('feature_pub_date', models.DateTimeField(verbose_name='date published')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Category')),
            ],
            options={
                'verbose_name_plural': 'features',
            },
        ),
    ]
