# Generated by Django 2.1.4 on 2018-12-06 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='feature_status',
            field=models.BooleanField(choices=[(1, 'Active'), (0, 'Inactive')], default=0),
        ),
    ]
