# Generated by Django 2.1.4 on 2018-12-06 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_main', models.CharField(max_length=100)),
                ('weather_desc', models.CharField(max_length=200)),
                ('weather_temp', models.FloatField(default=0.0)),
                ('weather_pressure', models.IntegerField(default=0)),
                ('weather_humidity', models.IntegerField(default=0)),
                ('weather_temp_min', models.FloatField(default=0.0)),
                ('weather_temp_max', models.FloatField(default=0.0)),
                ('wind_speed', models.IntegerField(default=0)),
                ('wind_degree', models.IntegerField(default=0)),
                ('weather_datetime', models.IntegerField(default=0)),
                ('clouds_all', models.IntegerField(default=0)),
                ('sys_sunrise', models.IntegerField(default=0)),
                ('sys_sunset', models.IntegerField(default=0)),
                ('weather_pub_date', models.DateTimeField(verbose_name='date published')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Location')),
            ],
            options={
                'verbose_name_plural': 'weathers',
            },
        ),
    ]
